apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ucu-de-devops-hw4-part-3
  name: ucu-de-devops-hw4-part-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ucu-de-devops-hw4-part-3
  template:
    metadata:
      labels:
        app: ucu-de-devops-hw4-part-3
    spec:
      containers:
        - image: ucu-de-devops-hw4-part-3
          name: ucu-de-devops-hw4-part-3
          ports:
            - name: http
              containerPort: 8050
