apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-green
images:
- name: ucu-de-devops-hw4-part-3
  newName: theviach/ucu-de-devops-hw4-part-3
  newTag: 9dc040a8a3c7bab0a6b3e3e5defe880316f9faf7
