apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: ucu-de-devops-hw4-part-3
  newName: theviach/ucu-de-devops-hw4-part-3
  newTag: e61a5bdd4c55b65a05473f99ec4720d0e511bdfe
