apiVersion: v1
kind: Service
metadata:
  labels:
    app: ucu-de-devops-hw4-part-3
  name: ucu-de-devops-hw4-part-3
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: ucu-de-devops-hw4-part-3
  type: ClusterIP
